import { FieldDefinition } from '../types';
export const fieldDefinitions: FieldDefinition[] = [
  {
    key: 'name',
    label: 'Name',
    type: 'text',
    operators: ['equals', 'contains', 'startsWith', 'endsWith', 'doesNotContain'],
  },
  {
    key: 'email',
    label: 'Email',
    type: 'text',
    operators: ['equals', 'contains', 'startsWith', 'endsWith', 'doesNotContain'],
  },
  {
    key: 'department',
    label: 'Department',
    type: 'singleSelect',
    operators: ['is', 'isNot'],
    options: ['Engineering', 'Design', 'Marketing', 'Sales', 'HR', 'Finance', 'Operations'],
  },
  {
    key: 'role',
    label: 'Role',
    type: 'text',
    operators: ['equals', 'contains', 'startsWith', 'endsWith', 'doesNotContain'],
  },
  {
    key: 'salary',
    label: 'Salary',
    type: 'amount',
    operators: ['equals', 'greaterThan', 'lessThan', 'greaterThanOrEqual', 'lessThanOrEqual', 'between'],
  },
  {
    key: 'joinDate',
    label: 'Join Date',
    type: 'date',
    operators: ['between'],
  },
  {
    key: 'isActive',
    label: 'Active',
    type: 'boolean',
    operators: ['is'],
  },
  {
    key: 'skills',
    label: 'Skills',
    type: 'multiSelect',
    operators: ['in', 'notIn'],
    options: [
      'React',
      'TypeScript',
      'Node.js',
      'GraphQL',
      'Python',
      'Java',
      'AWS',
      'Docker',
      'Kubernetes',
      'SQL',
      'MongoDB',
      'Vue.js',
      'Angular',
      'Figma',
      'Sketch',
    ],
  },
  {
    key: 'address.country',
    label: 'Country',
    type: 'singleSelect',
    operators: ['is', 'isNot'],
    options: ['USA'],
    path: 'address.country',
  },
  {
    key: 'address.city',
    label: 'City',
    type: 'singleSelect',
    operators: ['is', 'isNot'],
    options: [
      'San Francisco',
      'New York',
      'Austin',
      'Seattle',
      'Boston',
      'Chicago',
      'Los Angeles',
      'Denver',
    ],
    path: 'address.city',
  },
  {
    key: 'address.state',
    label: 'State',
    type: 'singleSelect',
    operators: ['is', 'isNot'],
    options: ['CA', 'NY', 'TX', 'WA', 'MA', 'IL', 'CO'],
    path: 'address.state',
  },
  {
    key: 'projects',
    label: 'Projects Count',
    type: 'number',
    operators: ['equals', 'greaterThan', 'lessThan', 'greaterThanOrEqual', 'lessThanOrEqual', 'between'],
  },
  {
    key: 'performanceRating',
    label: 'Performance Rating',
    type: 'number',
    operators: ['equals', 'greaterThan', 'lessThan', 'greaterThanOrEqual', 'lessThanOrEqual', 'between'],
  },
];

export const getFieldDefinition = (key: string): FieldDefinition | undefined => {
  return fieldDefinitions.find((field) => field.key === key);
};

export const operatorLabels: Record<string, string> = {
  equals: 'Equals',
  contains: 'Contains',
  startsWith: 'Starts With',
  endsWith: 'Ends With',
  doesNotContain: 'Does Not Contain',
  greaterThan: 'Greater Than',
  lessThan: 'Less Than',
  greaterThanOrEqual: 'Greater Than or Equal',
  lessThanOrEqual: 'Less Than or Equal',
  between: 'Between',
  is: 'Is',
  isNot: 'Is Not',
  in: 'In',
  notIn: 'Not In',
};
